config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#root"

  resources :users
  resource :session
  resources :photos
  resources :upvotes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_many :upvotes, dependent: :destroy
  has_attached_file :image, default_url: "missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/upvote.rb
class Upvote < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

app/models/user.rb
class User < ActiveRecord::Base

  validates :f_name, :l_name, :email, :session_token, :password_digest, presence: true
  validates :session_token, :email, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  has_many :photos, dependent: :destroy
  has_many :upvotes, dependent: :destroy

  attr_reader :password
  after_initialize :ensure_session_token

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email);
    return nil unless user
    user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    password_digest.is_password?(password)
  end

  def password_digest
    BCrypt::Password.new(super)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
  end

  private

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def currently_signed_in
    return nil unless session[:session_token]
    @currently_signed_in ||= User.find_by(session_token: session[:session_token])
  end

  def sign_in!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

  def sign_out!
    currently_signed_in.try(:reset_session_token!)
    session[:session_token] = nil
  end

  def is_signed_in?
    !!currently_signed_in
  end

  def require_signed_in!
    redirect_to new_session_url unless is_signed_in?
  end

  private

  def belongs_to_current_user(photo)
    return false if !is_signed_in?
    photo.user.id == currently_signed_in.id
  end

  helper_method :belongs_to_current_user
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:destroy]
  def create
    if !params[:photo]
      respond_to do |format|
        format.html { redirect_to root_url }
        format.js
        return
      end
    end
    @photo = Photo.new(photo_params)
    @photo.user = currently_signed_in

    respond_to do |format|
      if @photo.save
        format.html { redirect_to root_url }
      else
        format.js
        return
      end
    end
  end

  def destroy
    @photo.destroy
    redirect_to root_url
  end

  private

  def set_photo
    @photo = Photo.find(params[:id])
  end

  def photo_params
    params.require(:photo).permit(:image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email],
                                     params[:user][:password])
    respond_to do |format|
      if @user
        sign_in!(@user)
        format.html { redirect_to root_url }
      else
        format.js
      end
    end

  end

  def destroy
    sign_out!
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  # before_action :require_signed_in!
  def root
    @is_signed_in = is_signed_in?
    @photo = Photo.new
    @photos = Photo.all.order({ created_at: :desc })
    @user = User.new
    render :index
  end
end

app/controllers/upvotes_controller.rb
class UpvotesController < ApplicationController
  def create
    @upvote = Upvote.find_by(photo_id: params[:user][:photo], user_id: currently_signed_in.id)

    respond_to do |format|
      if @upvote
        return if @upvote.value == params[:user][:value]
        @upvote.update!(value: params[:user][:value])
        @photo = @upvote.photo
        format.js
      else
        @upvote = Upvote.new(
          photo_id: params[:user][:photo],
          user_id: currently_signed_in.id,
          value: params[:user][:value]
        )

        @photo = @upvote.photo
        @upvote.save!
        format.js
      end
    end
  end

  private

  def upvote_params
    params.require(:upvote).permit(:user, :photo, :value)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        sign_in!(@user)
        format.html { redirect_to root_url }
      else
        format.js
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:f_name, :l_name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<nav class="footer">

</nav>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="nav-wrapper">
  <div class="nav">
    <a href="#">twzzlr</a>
    <div class="actions">
      <% if @is_signed_in %>
        <form action="<%= session_url %>" method="post">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
          <input type="hidden" name="_method" value="delete">
          <button class="sign-out">sign out</button>
        </form>
      <% else %>
        <button data-toggle="modal" data-target="#signIn">Sign In</button>
        <button data-toggle="modal" data-target="#signUp">Sign Up</button>
      <% end %>
    </div>

    <%= render partial: 'sessions/new' %>
    <%= render partial: 'users/new' %>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li class='nav-item'><%= link_to 'About', page_path('about'), class: 'nav-link' %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Twzzlr" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Twzzlr" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/photos/_errors.html.erb
<div class="alert alert-danger" role="alert">
  <div>- Error uploading photo</div>
</div>

app/views/photos/_form.html.erb
<div class="photos-form">
  <%= form_for(@photo, multipart: true, remote: true) do |f| %>
    <div id="photos_error"></div>

    <div class="field">
      <%= f.label :image %>
      <%= f.file_field :image %>
    </div>
    <div class="actions">
      <%= f.submit 'Upload photo' %>
    </div>
  <% end %>
</div>

app/views/photos/_show.html.erb
<div class="photos">
  <% @photos.each {|photo| %>
    <div class="image">
      <div class="image-header">
        <%= photo.user.f_name %> <%= photo.user.l_name %>
      </div>
      <img src="<%= photo.image.url %>" />
      <div class="image-footer">
        <% if @is_signed_in %>
          <div class="upvotes-input">
            <%= form_for(@user, :url => url_for(:controller => 'upvotes', :action => 'create'), remote: true) do |f| %>
              <%= f.hidden_field :photo, value: photo.id  %>
              <%= f.hidden_field :value, value: 1  %>
              <button class="icon-input">
                <%= octicon "thumbsup", :height => 25,  :class => "right left" %>
              </button>
            <% end %>
            <%= form_for(@user, :url => url_for(:controller => 'upvotes', :action => 'create'), remote: true) do |f| %>
              <%= f.hidden_field :photo, value: photo.id  %>
              <%= f.hidden_field :value, value: -1  %>
              <button class="icon-input">
                <%= octicon "thumbsdown", :height => 25,  :class => "right left" %>
              </button>
            <% end %>
          </div>
        <% end %>
        <span id="upvotes_count_<%= photo.id %>">
          <%= render partial: "upvotes/count", :locals => { photo: photo } %>
        </span>

        <% if belongs_to_current_user(photo) %>
          <form action="<%= photos_url %>/<%= photo.id %>" method="post">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <input type="hidden" name="_method" value="delete">
            <button class="icon-input">
              <%= octicon "trashcan", :height => 28,  :class => "right left" %>
            </button>
          </form>
        <% end %>
      </div>
    </div>
  <% } %>
</div>

app/views/photos/create.js.erb
$("#photos_error").html("<%=j render :partial => 'photos/errors' %>")

app/views/static_pages/index.html.erb
<%= render partial: "layouts/navigation", :locals => {is_signed_in: @is_signed_in} %>

<div class="main">
  <p id="notice"><%= notice %></p>
  <% if @currently_signed_in %>
    <%= render partial: "photos/form", :locals => {photo: @photo} %>
  <% end %>

  <%= render partial: "photos/show", :locals => {photos: @photos, is_signed_in: @is_signed_in} %>
</div>


<%= render partial: "layouts/footer" %>

app/views/upvotes/_count.html.erb
<span>
  <%= photo.upvotes.map {|obj| obj.value}.inject(0){|sum, x| sum + x} %> points
</span>

app/views/upvotes/create.js.erb
$("#upvotes_count_<%= @photo.id %>").html("<%=j render :partial => 'upvotes/count', :locals => { photo: @photo } %>")

app/views/users/_errors.html.erb
<div class="alert alert-danger" role="alert">
  <% @user.errors.full_messages.each do |message| %>
    <div>- <%= message %></div>
  <% end %>
</div>

app/views/users/_new.html.erb
<!-- Modal -->
<div class="modal fade" id="signUp" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      </div>
      <div class="modal-body">
        <div id="errors_div"></div>
        <%= form_for(@user, remote: true) do |f| %>
          <strong><%= f.label "First Name" %></strong>
          <br>
          <%= f.text_field :f_name, class: "text-input" %>
          <br>
          <div class="spacer-small"></div>
          <strong><%= f.label "Last Name" %></strong>
          <br>
          <%= f.text_field :l_name, class: "text-input" %>
          <br>
          <div class="spacer-small"></div>
          <strong><%= f.label "Email" %></strong>
          <br>
          <%= f.text_field :email, class: "text-input" %>
          <br>
          <div class="spacer-small"></div>
          <strong><%= f.label "Password" %></strong>
          <br>
          <%= f.password_field :password, class: "text-input" %>
          <br>
          <div class="spacer-medium"></div>
          <%= f.submit "Sign Up", class: "cta-button" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/create.js.erb
$("#errors_div").html("<%=j render :partial => 'users/errors' %>")

app/views/visitors/index.html.erb
<h3 className="test">Hello, world</h3>
<div class="container">
  <div class="row">
    <div class="col-sm">
      One of three columns
    </div>
    <div class="col-sm">
      One of three columns
    </div>
    <div class="col-sm">
      One of three columns
    </div>
  </div>
</div>